# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VideoChatRoom' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VideoChatRoom
  pod 'UpstraUIKit', '1.11.4', :source => "https://github.com/EkoCommunications/EkoMessagingSDKUIKit.git"
  pod 'MenuItemKit', '~> 4.0.0'
end
